---
- name: excel to CSV file conversion
  hosts: localhost
  gather_facts: false
- import_playbook: xls_to_csv.yml
- name: CSV to yaml file converstion
  hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: "Conversion process begins"   
- import_playbook: csv_to_yml.yml
    
- name: Conversion process end
  hosts: localhost 
  tasks:
    - debug: 
        msg: "Conversion process completed successfully"
- name: Change creation process begins
  hosts: localhost
- import_playbook: change_creation_yaml.yml
- name: Change creation process end
  hosts: localhost
  tasks:
    - debug: 
        msg: "change creation process completed successfully"
